/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-09-29 05:06:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.renrentui.renrencore.util.PropertyUtils;

public final class _404_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PropertyUtils");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath = PropertyUtils.getProperty("java.renrenadmin.url");
    response.setStatus(HttpServletResponse.SC_OK);

      out.write("\r\n");
      out.write("<img src=\"");
      out.print(basePath);
      out.write("/img/404sz.jpg\" id=\"img1\" />\r\n");
      out.write("\t<input id=\"indexbtn\" type=\"button\" value=\"返回首页\">\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\t<span id=\"timespan\">5</span>秒后自动返回管理后台首页\r\n");
      out.write("\t</p>\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){ \r\n");
      out.write("\tvar intervalId=setInterval(function(){\r\n");
      out.write("\t\t\tvar timeSection=document.getElementById('timespan');\r\n");
      out.write("\t\t\tvar second=parseInt(timeSection.innerHTML);\r\n");
      out.write("\t\t\tif(second<=0){\r\n");
      out.write("\t\t\t\tclearInterval(intervalId);\r\n");
      out.write("\t\t\t\twindow.location.href = \"");
      out.print(basePath);
      out.write("/account/list\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\ttimeSection.innerHTML=second-1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},1000);\r\n");
      out.write("\r\n");
      out.write("\t$(\"#indexbtn\").click(function() {\r\n");
      out.write("\t\twindow.location.href = \"");
      out.print(basePath);
      out.write("/account/list\";\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
