/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-09-29 05:16:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.renrentui.renrencore.util.PropertyUtils;
import java.io.*;

public final class _500_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PropertyUtils");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath = PropertyUtils.getProperty("java.renrenadmin.url");
    //response.setStatus(HttpServletResponse.SC_OK);

      out.write("\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$(\"#showErrorMessageButton\").click(function() {\r\n");
      out.write("\t\t$(\"#errorMessageDiv\").toggle();\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("    <div class=\"middle-box text-center animated fadeInDown\">\r\n");
      out.write("        <h1>500</h1>\r\n");
      out.write("        <h3 class=\"font-bold\">服务器内部错误</h3>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"error-desc\">\r\n");
      out.write("            服务器好像出错了...\r\n");
      out.write("            <br/>您可以返回主页看看\r\n");
      out.write("            <br/><a href=\"");
      out.print(basePath);
      out.write("/account/list\"  class=\"btn btn-primary m-t\">主页</a>\r\n");
      out.write("            <br/><a id=\"showErrorMessageButton\"  href=\"javascript:void(0)\">详细错误信息</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<div id=\"errorMessageDiv\" style=\"display:none;\">\r\n");
      out.write("\t<pre>\r\n");
      out.write("                ");

                	try {
                		//全部内容先写到内存，然后分别从两个输出流再输出到页面
                		ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                		PrintStream printStream = new PrintStream(byteArrayOutputStream);

                		printStream.println();

                		printStream.println("访问的路径: "+ request.getAttribute("javax.servlet.forward.request_uri"));
                		printStream.println();

                		Enumeration<String> e = request.getParameterNames();
                		if (e.hasMoreElements()) {
                			printStream.println("请求中的Parameter包括：");
                			while (e.hasMoreElements()) {
                				String key = e.nextElement();
                				printStream.println(key + "="+ request.getParameter(key));
                			}
                			printStream.println();
                		}
                		printStream.println("异常信息:");
                		Object msg = request.getAttribute("exception");
                		if (msg != null) {
                			printStream.println(msg);
                		} else {
                			printStream.println(exception.getClass() + " : "+ exception.getMessage());
                		}
                		printStream.println();
                		printStream.println("堆栈信息");
                		Object stackTrace = request.getAttribute("stackTrace");
                		if (stackTrace != null) {
                			printStream.println(stackTrace);
                		} else {
                			exception.printStackTrace(printStream);
                		}
                		printStream.println();
                		out.print(byteArrayOutputStream); //输出到网页
                	} catch (Exception ex) {
                		ex.printStackTrace();
                	}
                
      out.write("\r\n");
      out.write("            </pre>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
