/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-09-29 07:05:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.template;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.renrentui.renrencore.util.PropertyUtils;
import com.renrentui.renrenapi.service.inter.IMenuInfoService;
import com.renrentui.renrencore.util.SpringBeanHelper;
import com.renrentui.renrenentity.MenuInfo;
import java.util.List;
import java.util.ArrayList;
import com.renrentui.renrenadmin.common.UserContext;

public final class leftmenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.5.jar", Long.valueOf(1435848268796L));
    _jspx_dependants.put("jar:file:/D:/renrenditui/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/renrenadmin/WEB-INF/lib/tiles-jsp-3.0.5.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1411313530000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.renrentui.renrenentity.MenuInfo");
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PropertyUtils");
    _jspx_imports_classes.add("com.renrentui.renrencore.util.SpringBeanHelper");
    _jspx_imports_classes.add("com.renrentui.renrenapi.service.inter.IMenuInfoService");
    _jspx_imports_classes.add("com.renrentui.renrenadmin.common.UserContext");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath =PropertyUtils.getProperty("java.renrenadmin.url");
	IMenuInfoService menuService = SpringBeanHelper.getCustomBeanByType(IMenuInfoService.class);
	
	UserContext context = UserContext.getCurrentContext(request);
	if(context == null){
		response.sendRedirect(basePath);
		return;
	}
	List<MenuInfo> menuList = menuService.getMenuListByUserID(context.getId());
    String viewPath =request.getAttribute("viewPath").toString();

      out.write("\r\n");
      out.write("<nav class=\"navbar-default navbar-static-side\" role=\"navigation\">\r\n");
      out.write("\t<div class=\"sidebar-collapse\">\r\n");
      out.write("\t\t<ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("\t\t\t<li class=\"nav-header\">\r\n");
      out.write("\t\t\t\t<div class=\"dropdown profile-element\">\r\n");
      out.write("\t\t\t\t\t<span> <img alt=\"image\" class=\"img-circle\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(basePath);
      out.write("/img/profile_small.jpg\" />\r\n");
      out.write("\t\t\t\t\t</span> <a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"clear\"> <span class=\"block m-t-xs\"> <strong\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"font-bold\">");
      out.print(context.getLoginName() );
      out.write("</strong>\r\n");
      out.write("\t\t\t\t\t\t</span> <span class=\"text-muted text-xs block\">");
      out.print(context.getUserName() );
      out.write(" <b\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"caret\"></b></span>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu animated fadeInRight m-t-xs\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(basePath );
      out.write("/account/changepwd\">修改密码</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a href=\"contacts.html\">联系方式</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a href=\"mailbox.html\">消息</a></li> -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(basePath );
      out.write("/account/logoff\">注销</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo-element\">IN+</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

			        String parentClass="";
					for (MenuInfo menu : menuList) {
						if (menu.getParId() == 0) {
							parentClass="";
							List<MenuInfo> data=new ArrayList<>();
							for (MenuInfo itemMenu : menuList) {
								if (itemMenu.getParId() == menu.getId()
										&& itemMenu.getIsButton() == false) {
									if(viewPath.equals(itemMenu.getUrl().substring(1))){
										parentClass=" class='active' ";
									}
									data.add(itemMenu);
								}
							}
							if(data.size()>0){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li ");
      out.print(parentClass);
      out.write("><a href=\"#\"><i class=\"fa fa-th-large\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"nav-label\">");
      out.print(menu.getMenuName());
      out.write("</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa arrow\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav nav-second-level\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

								for (MenuInfo submenu : data) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li ");
      out.print(viewPath.equals(submenu.getUrl().substring(1))?"class='active'":"");
      out.write("><a href=\"");
      out.print(basePath+submenu.getUrl());
      out.write('"');
      out.write('>');
      out.print(submenu.getMenuName());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t");

							}	
					}
				}	
			
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
