package com.renrentui.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-10-15T15:23:57.777+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SmsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SmsSoap {

    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "com.renrentui.sms.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "com.renrentui.sms.HelloWorldResponse")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String helloWorld();

    @WebMethod(operationName = "SendSmsSaveLog", action = "http://tempuri.org/SendSmsSaveLog")
    @RequestWrapper(localName = "SendSmsSaveLog", targetNamespace = "http://tempuri.org/", className = "com.renrentui.sms.SendSmsSaveLog")
    @ResponseWrapper(localName = "SendSmsSaveLogResponse", targetNamespace = "http://tempuri.org/", className = "com.renrentui.sms.SendSmsSaveLogResponse")
    @WebResult(name = "SendSmsSaveLogResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSmsSaveLog(
        @WebParam(name = "mobile", targetNamespace = "http://tempuri.org/")
        java.lang.String mobile,
        @WebParam(name = "content", targetNamespace = "http://tempuri.org/")
        java.lang.String content,
        @WebParam(name = "supplierId", targetNamespace = "http://tempuri.org/")
        int supplierId,
        @WebParam(name = "smsSource", targetNamespace = "http://tempuri.org/")
        java.lang.String smsSource
    );
}
