/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-09-29 05:06:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.renrentui.renrencore.consts.GlobalSettings;
import com.renrentui.renrencore.util.PropertyUtils;
import com.renrentui.renrenadmin.common.LoginUtil;
import com.renrentui.renrencore.util.PropertyUtils;
import com.renrentui.renrenadmin.common.LoginUtil;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PropertyUtils");
    _jspx_imports_classes.add("com.renrentui.renrenadmin.common.LoginUtil");
    _jspx_imports_classes.add("com.renrentui.renrencore.consts.GlobalSettings");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String basePath = PropertyUtils.getProperty("java.renrenadmin.url");

      out.write('\r');
      out.write('\n');

	boolean isLogin = LoginUtil.checkIsLogin(request,response);
	if(isLogin){
		//如果登录,跳转到首页
		response.sendRedirect(basePath+"/account/list");
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\" />\r\n");
      out.write("<title>人人地推管理后台</title>\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("/css/animate.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"");
      out.print(basePath);
      out.write("/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/js/jquery-2.1.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"gray-bg\">\r\n");
      out.write("\t<div class=\"middle-box text-center loginscreen  animated fadeInDown\">\r\n");
      out.write("\t\t<div style=\"margin-top: 100px;\">\r\n");
      out.write("\t\t\t<!-- \t\t\t<div>\r\n");
      out.write("\t\t\t\t<h1 class=\"logo-name\">H+</h1>\r\n");
      out.write("\t\t\t</div> -->\r\n");
      out.write("\t\t\t<h2>人人地推管理后台</h2>\r\n");
      out.write("\t\t\t<form class=\"m-t\" role=\"form\" action=\"");
      out.print(basePath);
      out.write("/account/login\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"用户名\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"\" name=\"username\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"密码\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"\" name=\"password\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"code\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 100px; float: left;\" placeholder=\"验证码\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"\"> <img src=\"");
      out.print(basePath );
      out.write("/account/code?x=Math.random();\" id=\"imgCode\"\r\n");
      out.write("\t\t\t\t\t\theight=\"30px\" style=\"float: left;\" onclick=\"changeCodeImg()\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label> <input type=\"checkbox\" name=\"rememberMe\" id=\"rememberMe\" value=\"1\" class=\"i-checks\">自动登录\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-primary block full-width m-b\">登\r\n");
      out.write("\t\t\t\t\t录</button>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<h3 style=\"color:red;\">");
      out.print(request.getAttribute("error")==null?"": request.getAttribute("error"));
      out.write("</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction changeCodeImg(){\r\n");
      out.write("\t\tvar ran = Math.random();\r\n");
      out.write("\t\tdocument.getElementById(\"imgCode\").src = \"");
      out.print(basePath );
      out.write("/account/code?x=\"+ran;\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- Mainly scripts -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
