/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-09-29 09:12:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.business;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.renrentui.renrencore.util.PropertyUtils;
import com.renrentui.renrenentity.RoleInfo;
import java.util.List;
import com.renrentui.renrencore.util.HtmlHelper;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PropertyUtils");
    _jspx_imports_classes.add("com.renrentui.renrenentity.RoleInfo");
    _jspx_imports_classes.add("com.renrentui.renrencore.util.HtmlHelper");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String basePath =PropertyUtils.getProperty("java.renrenadmin.url");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#map_contain {\r\n");
      out.write("    height: 90%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    max-width: none;\r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("    max-width: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#control {\r\n");
      out.write("width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"wrapper wrapper-content animated fadeInRight\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<form method=\"POST\" action=\"#\" class=\"form-horizontal\" id=\"searchForm\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-4 control-label\">公司名称:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"txtCompanyName\"  id=\"txtCompanyName\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-4 control-label\">电话号码:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"txtPhoneNo\"  id=\"txtPhoneNo\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-4 control-label\">登陆名称:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"txtLoginName\"  id=\"txtLoginName\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-sm-4 control-label\">所在城市</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"txtCityName\"  id=\"txtCityName\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-w-m btn-primary\" id=btnSearch\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-left: 3px;height:30px;\">查询</button>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-w-m btn-primary\" \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"margin-left:3px;\" data-toggle=\"modal\" data-target=\"#myModal\" onclick=\"AddShow()\" id=\"btnAdd\">添加商户</button>\t\t\t \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<div class=\"ibox-content\" id=\"content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div> \r\n");
      out.write("<div tabindex=\"-1\" class=\"modal inmodal\" id=\"addBusiness\"\r\n");
      out.write("\trole=\"dialog\" aria-hidden=\"true\" style=\"display: none;\">\r\n");
      out.write("\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t<div class=\"modal-content animated bounceInRight\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<button class=\"close\" type=\"button\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">×</span><span class=\"sr-only\">关闭</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title\">添加商户</h4> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<small class=\"font-bold\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t            <br>\r\n");
      out.write("\t\t\t             <div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label >公司名称：</label> \r\n");
      out.write("\t\t\t                    <input  name=\"txtCompanyNameA\" id=\"txtCompanyNameA\" type=\"text\">\t\t\t                    \r\n");
      out.write("\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label>电话号码：</label> \r\n");
      out.write("\t\t\t                <input  name=\"txtPhoneNoA\" id=\"txtPhoneNoA\" type=\"text\">\t\t\t\t\t               \r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t            <div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label >登录名称：</label> \r\n");
      out.write("\t\t\t                    <input name=\"txtLoginNameA\" id=\"txtLoginNameA\" type=\"text\">\r\n");
      out.write("\t\t\t            </div> \r\n");
      out.write("\t\t\t            <div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label >地&nbsp;&nbsp;址：</label> \r\n");
      out.write("\t\t\t                    <input  name=\"txtAddressA\" id=\"txtAddressA\" type=\"text\">\r\n");
      out.write("\t\t\t            </div> \r\n");
      out.write("\t\t\t            <div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label >所属城市：</label> \r\n");
      out.write("\t\t\t                    <input  name=\"txtCityNameA\" id=\"txtCityNameA\" type=\"text\">\r\n");
      out.write("\t\t\t            </div> \r\n");
      out.write("\t\t\t             <div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label >站&nbsp;&nbsp;点：</label> \r\n");
      out.write("\t\t\t                    <input  name=\"txtWebSiteA\" id=\"txtWebSiteA\" type=\"text\">\r\n");
      out.write("\t\t\t            </div> \r\n");
      out.write("\t\t\t        </fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-white\" type=\"button\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-primary\" type=\"button\" id=btnModifyGroupBusiness onclick=\"AddBusiness()\">保存</button>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t</small>\r\n");
      out.write("\t\t</div>  \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var jss={\r\n");
      out.write("\t\tsearch:function(currentPage){\t\r\n");
      out.write("\t\t\t var companyName = $(\"#txtCompanyName\").val();\t\t\t\t   \r\n");
      out.write("\t\t\t var phoneNo = $(\"#txtPhoneNo\").val();\r\n");
      out.write("\t\t\t var loginName = $(\"#txtLoginName\").val();\r\n");
      out.write("\t\t\t var cityName = $(\"#txtCityName\").val();\r\n");
      out.write("\t\t\t var paramaters = { \r\n");
      out.write("\t\t\t\t\t \"currentPage\":currentPage,\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t \"companyName\":companyName,\r\n");
      out.write("\t\t\t\t\t \"phoneNo\":phoneNo,\r\n");
      out.write("\t\t\t\t\t \"loginName\":loginName,\r\n");
      out.write("\t\t\t\t\t \"cityName\":cityName,\r\n");
      out.write("\t\t\t\t\t m:Math.round()\r\n");
      out.write("\t\t\t\t\t };\r\n");
      out.write("\t\t        var url = \"");
      out.print(basePath);
      out.write("/business/listdo\";\r\n");
      out.write("\t\t        $.ajax({\r\n");
      out.write(" \t\t            type: 'POST',\r\n");
      out.write(" \t\t            url: url,\r\n");
      out.write(" \t\t            data: paramaters,\r\n");
      out.write(" \t\t            success: function (result) {   \t\r\n");
      out.write(" \t\t            \t$(\"#content\").html(result);               \r\n");
      out.write(" \t\t            }\r\n");
      out.write(" \t\t        });  \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\r\n");
      out.write("jss.search(1);\r\n");
      out.write("$(\"#btnSearch\").click(function(){\r\n");
      out.write("\tjss.search(1);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function AddShow(){\r\n");
      out.write("    $('#addBusiness').modal('show');\r\n");
      out.write("}\r\n");
      out.write("//保存商户\r\n");
      out.write("function AddBusiness(){\r\n");
      out.write("\tvar companyName= $('#txtCompanyNameA').val().trim();\r\n");
      out.write("\tvar phoneNo= $('#txtPhoneNoA').val().trim();\t\r\n");
      out.write("    var loginName = $('#txtLoginNameA').val().trim();\r\n");
      out.write("    var address= $('#txtAddressA').val().trim();\r\n");
      out.write("    var cityName= $('#txtCityNameA').val().trim();\r\n");
      out.write("    var webSite= $('#txtWebSiteA').val().trim();    \r\n");
      out.write("    var reg=/[\\u4e00-\\u9fa5]+/;   \r\n");
      out.write("    \r\n");
      out.write("    if(companyName.trim().length <=4 || companyName.trim().length>30){\r\n");
      out.write("    \talert(\"公司名称必须在5-30个字符\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }\r\n");
      out.write("    if (reg.test(loginName)){\r\n");
      out.write("    \talert(\"登录账号不能为中文字符\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }\r\n");
      out.write("    if(loginName.trim().length <6 || loginName.trim().length>20){\r\n");
      out.write("    \talert(\"登录账号除中文外6-20位字符\");\r\n");
      out.write("    \treturn;\r\n");
      out.write("    }   \r\n");
      out.write("    \r\n");
      out.write("    var paramaters = {\r\n");
      out.write("            \"companyName\": companyName,\r\n");
      out.write("            \"phoneNo\": phoneNo,\r\n");
      out.write("            \"loginName\": loginName,\r\n");
      out.write("            \"address\": address,\r\n");
      out.write("            \"cityName\": cityName,\r\n");
      out.write("            \"webSite\": webSite                 \r\n");
      out.write("        };\r\n");
      out.write("   var url = \"");
      out.print(basePath);
      out.write("/business/addbusiness\";\r\n");
      out.write("   var la= layer.confirm('是否确认创建商户？', {\r\n");
      out.write("\t    btn: ['确认','取消'], //按钮\r\n");
      out.write("\t    shade: false //显示遮罩\r\n");
      out.write("\t},function(){\r\n");
      out.write("\t\tlayer.close(la);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t           type: 'POST',\r\n");
      out.write("\t           url: url,\r\n");
      out.write("\t           data: paramaters,\r\n");
      out.write("\t           success: function (result) {\r\n");
      out.write("\t        \t   window.location.href = \"");
      out.print(basePath);
      out.write("/business/list\";\r\n");
      out.write("\t        \t   //alert(result.message);\r\n");
      out.write("\t             ");
      out.write("\r\n");
      out.write("\t        \t  \r\n");
      out.write("\t           }\r\n");
      out.write("\t       });\r\n");
      out.write("\t});\r\n");
      out.write("   \t    \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
