/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2015-09-29 07:42:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.business;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.renrentui.renrenentity.common.PagedResponse;
import com.renrentui.renrencore.util.PageHelper;
import java.util.ArrayList;
import com.renrentui.renrenentity.Business;
import java.util.List;
import com.renrentui.renrencore.util.PropertyUtils;

public final class listdo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.renrentui.renrenentity.Business");
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PageHelper");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.renrentui.renrencore.util.PropertyUtils");
    _jspx_imports_classes.add("com.renrentui.renrenentity.common.PagedResponse");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String basePath =PropertyUtils.getProperty("java.renrenadmin.url");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table\r\n");
      out.write("\tclass=\"table table-striped table-bordered table-hover dataTables-example\">\r\n");
      out.write("\t<thead>\r\n");
      out.write("\t\t<tr class=\"tdbg\">\r\n");
      out.write("\t\t\t<th width=\"%5\">编号</th>\r\n");
      out.write("\t\t\t<th width=\"10%\">公司名称</th>\r\n");
      out.write("\t\t\t<th width=\"10%\">电话号码</th>\r\n");
      out.write("\t\t\t<th width=\"10%\">登陆名称</th>\r\n");
      out.write("\t\t\t<th width=\"10%\">地址</th>\r\n");
      out.write("\t\t\t<th width=\"10%\">所属城市</th>\r\n");
      out.write("\t\t\t<th width=\"10%\">站点</th>\t\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			PagedResponse<Business> responsePageList = (PagedResponse<Business>)request.getAttribute("listData");
			List<Business> data=responsePageList.getResultList();
			for (int i = 0; i < data.size(); i++) {			
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getId());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getCompanyName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getPhoneNo());
      out.write("</td>\t\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getLoginName());
      out.write("</td>\t\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getAddress());
      out.write("</td>\t\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getCityName());
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(data.get(i).getWebSite());
      out.write("</td>\t\t\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.print(PageHelper.getPage(responsePageList.getPageSize(),
		responsePageList.getCurrentPage(), responsePageList.getTotalRecord(),
		responsePageList.getTotalPage()));
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
