
package com.renrentui.sms.saltlight;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-04T13:12:49.320+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class SmsSoap_SmsSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Sms");

    private SmsSoap_SmsSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Sms.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Sms ss = new Sms(wsdlURL, SERVICE_NAME);
        SmsSoap port = ss.getSmsSoap();  
        
        {
        System.out.println("Invoking helloWorld...");
        java.lang.String _helloWorld__return = port.helloWorld();
        System.out.println("helloWorld.result=" + _helloWorld__return);


        }
        {
        System.out.println("Invoking sendSmsSaveLog...");
        java.lang.String _sendSmsSaveLog_mobile = "";
        java.lang.String _sendSmsSaveLog_content = "";
        int _sendSmsSaveLog_supplierId = 0;
        java.lang.String _sendSmsSaveLog_smsSource = "";
        java.lang.String _sendSmsSaveLog__return = port.sendSmsSaveLog(_sendSmsSaveLog_mobile, _sendSmsSaveLog_content, _sendSmsSaveLog_supplierId, _sendSmsSaveLog_smsSource);
        System.out.println("sendSmsSaveLog.result=" + _sendSmsSaveLog__return);


        }

        System.exit(0);
    }

}
